# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dc8c4ad9b9371148ddf1a888b603db0a07a21da89e61a97a17ce07d14af84777af7a09ec6d9e3b77b9d518e295c3986fa36e8f81b6d120909ed2700dce653d5

test:
  secret_key_base: 2dbac256219e352e4c723b4a1770c1870fc5d5c1981b367d31b6da7dd7631645f42532e6f378df71eaaafb9811a5923a539e3282211b5dd8f2bf6adae5235b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
